export const listATM = [
    {
        id: 'mb',
        status: 'active',
        linkImg: 'https://storage.googleapis.com/hyperlead-public/production/assets/offers/mbbankapp.png',
        name: 'Thẻ MB - Ngân hàng quân đội',
        linkA: 'https://hyperlead.tech/hlt1CF',
        linkIO: 'https://hyperlead.tech/hlX9yw',
        title: 'MB Bank - Hướng dẫn thủ tục làm thẻ ATM nhanh chóng',
        desc: [
            'App MBBank là ứng dụng của Ngân hàng Quân đội - MB bank, cho phép khách hàng thực hiện hầu hết giao dịch tài chính, thanh toán hàng ngày với thao tác đơn giản, thực hiện được mọi lúc, mọi nơi.',
            'Là ứng dụng được cài đặt trên điện thoại thông minh nên thường xuyên được nâng cấp,  mang đến trải nghiệm và sự thuận tiện tối ưu nhất cho khách hàng.',
            '- Mở tài khoản online: Mở mới ngay tài khoản MB online',
            '- Vay online: Thông tin về các khoản vay, Công cụ tính lãi vay',
            '- Tiết kiệm online: Gửi tiết kiệm online, lãi suất ưu đãi so với tại quầy',
            '- Thông tin tài khoản: Số dư/ sao kê tài khoản, Tiết kiệm, Khoản vay, Thế chấp',
            '- Thanh toán: Nạp tiền điện thoại, Thanh toán hóa đơn của hơn 70 nhà cung cấp (điện, nước, vé máy bay…)',

            ' ** Quy trình đăng ký **',
            'B1: Khách hàng truy cập vào link của HyperLead, tải và mở app MB Bank, chọn "Đăng ký ngay" ',
            'B2: Khách hàng nhập số điện thoại và xác thực OTP',
            'B3: Khách hàng chọn loại giấy tờ tuỳ thân (CMND/CCCD/Hộ chiếu) và chụp hai mặt giấy tờ',
            'B4: Khách hàng quay chân dung khuôn mặt và làm theo hướng dẫn của app',
            'B5: Khách hàng bổ sung thông tin email và tạo mật khẩu',
            'B6: Khách hàng tạo mã pin và lựa chọn tài khoản số đẹp',
            'B7: Khách hàng xác nhận thông tin và hoàn tất mở tài khoản.',
            'Hướng dẫn mở tài khoản MB Bank: <a href="https://docs.google.com/presentation/d/1dspYLF396atCqmsRg7vTNSLss1FMonJFhrIu0ti1afI/edit"> Xem tại đây </a>',
        ],
    },
    {
        id: 'techcombank',
        status: 'active',
        linkImg: 'https://storage.googleapis.com/hyperlead-public/production/assets/offers/logo/Techcombank cá nhân_logo 1.png',
        name: 'Thẻ Techcombank',
        linkA: 'https://hyperlead.tech/hlE69C',
        linkIO: 'https://hyperlead.tech/hlzuRg',
        title: 'TechcomBank - Hướng dẫn thủ tục làm thẻ ATM nhanh chóng',
        desc: [
            'Ngân hàng thương mại cổ phần Kỹ Thương Việt Nam (hay còn được gọi là Techcombank) là một ngân hàng cổ phần thương mại của Việt Nam, được thành lập năm 1993 với số vốn ban đầu 20 tỷ đồng.',
            'Techcombank được nhiều tổ chức Việt Nam và quốc tế trao các giải thưởng về tài chính - ngân hàng, và được coi là một trong những ngân hàng uy tín hàng đầu tại Việt Nam.',
            'Ưu đãi chính:',
            'Tự do chọn số tài khoản đẹp chỉ 1 đồng/Chọn tài khoản số đẹp như ý',
            'Tự do chọn thiết kế thẻ chuẩn gu của bạn',
            'Cash back 2%',
            'Sở hữu bộ đôi tài khoản & thẻ thanh toán chỉ 1 phút',
            'Mở tài khoản tiền gửi online lãi suất hấp dẫn lên đến 7.15%/năm',
            'Hoàn tiền 20% Phí bảo hiểm năm đầu tiên và không giới hạn số tiền được',
            'hoàn (Áp dụng cho tất cả sản phẩm bảo hiểm nhân thọ của Manulife Việt Nam được phân phối qua Techcombank) - <a href="https://techcombank.com/khach-hang-ca-nhan/bao-hiem/chuong-trinh-uu-dai/hoan-tien-20-phan-tram"> Link tham khảo </a>',
            ' ** Quy trình đăng ký ** ',
            'B1: Khách hàng truy cập vào link của HyperLead, tải và mở app Techcombank',
            'B2: Khách hàng chọn "Tôi là khách hàng mới" --> chọn "Tài khoản và thẻ thanh toán" --> chọn "Đăng ký tài khoản chuẩn" --> chọn "Mở tài khoản"',
            'B3: Khách hàng nhập số điện thoại và xác thực OTP',
            'B4: Khách hàng chọn loại giấy tờ tuỳ thân (CMND/CCCD/Hộ chiếu) --> chụp hai mặt giấy tờ --> xác thực thông tin',
            'B5: Khách hàng quay chân dung khuôn mặt và làm theo hướng dẫn của app',
            'B6: Khách hàng bổ sung thông tin, chọn số tài khoản và tạo mật khẩu',
            'B7: Khách hàng hoàn tất mở tài khoản và đăng nhập thành công',
            'B8: Khách hàng phát sinh giao dịch tối thiểu từ 10.000 VNĐ để nhận được 100.000 VNĐ',
            'Hướng dẫn mở tài khoản và phát sinh giao dịch: <a href="https://docs.google.com/presentation/d/1Gik71904XoDOJ6NC4ysB4H_lhXDKYJ9XsByD41naKKo/edit#slide=id.g23177e767f4_0_95"> Xem tại đây </a>'
        ]
    },
    {
        id: 'bidv',
        status: 'active',
        linkImg: 'https://storage.googleapis.com/hyperlead-public/production/assets/offers/Logo_BIDV.svg.png',
        name: 'Thẻ BIDV',
        linkA: 'https://hyperlead.tech/hlFNWt',
        linkIO: 'https://hyperlead.tech/hlFNWt',
        title: 'BIDV Bank - Hướng dẫn thủ tục làm thẻ ATM nhanh chóng',
        desc: [
            'Với mục tiêu nâng cao trải nghiệm khách hàng, Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV) - chi nhánh Ngọc Khánh ra mắt Dịch vụ Ngân hàng số SmartBanking thế hệ mới với giao diện và các tiện ích mới cho phép Khách hàng thực hiện liền mạch các giao dịch tài chính và tiện ích số trên các kênh ngân hàng số của BIDV. ',
            'BIDV Ngọc Khánh là chi nhánh đứng số 1 hệ thống về ngân hàng số tại BIDV và là chi nhánh duy nhất có phòng dịch vụ ngân hàng số tính đến thời điểm hiện tại.',
            '1. Chính sách Zero Phí',
            '- Miễn phí phí quản lý tài khoản (1TK) mặc định trên SmartBanking trong trường hợp có PSGD tài chính trên Smartbanking tháng liền trước.',
            '- Miễn phí phí duy trì Smartbanking',
            '- Miễn phí phí chuyển tiền online trong và ngoài BIDV trên Smartbanking',
            '- Miễn phí phí phát hành và phí thường niên trọn đời khi phát hành thẻ phi vật lý trên Smartbanking.',
            '- Miễn phí mở Tài khoản Chọn tên Như ý là SĐT trên SMB.',
            '- Không yêu cầu số dư tối thiểu.',
            '2. Chính sách khi sử dụng App Smartbanking (SMB)',
            '- Khách hàng đăng ký SMB và thực hiện đổi mật khẩu: Tặng ngay 10.000 VNĐ vào tài khoản.',
            '- Tặng thêm 100.000 VNĐ khi khách hàng phát sinh tối thiểu 03 loại giao dịch tài chính khác nhau ngay trong tháng đăng ký bao gồm: Giao dịch chuyển tiền; Giao dịch TTHĐ (điện, nước, internet, truyền hình...); Giao dịch thanh toán (QR Vnpay, taxi, đặt hoa, vé tàu/vé xe, khách sạn, xem phim…); Giao dịch nạp thẻ điện thoại; Giao dịch gửi TK online; Giao dịch đặt TK...',

            '** Quy trình đăng ký **',
            'Bước 1: Khách hàng truy cập vào ô "Đăng ký ngay"',
            'Bước 2: Khách hàng để lại thông tin Họ tên & SĐT --> nhấn "Gửi thông tin"',
            'Bước 3: Nhấn "Mở tài khoản ngay" và tải ứng dụng BIDV SmartBanking ==> Ghi nhận đơn chờ duyệt',
            'Bước 4: Khách hàng mở ứng dụng và điền thông tin cá nhân',
            'Bước 5: Khách hàng chụp giấy tờ tuỳ thân và chân dung theo hướng dẫn của ứng dụng',
            'Bước 6: Bổ sung thông tin và chọn chi nhánh mở tài khoản là chi nhánh Ngọc Khánh (bắt buộc)',
            'Bước 7: Xác thực OTP và hoàn tất đăng ký mở tài khoản',
            'Bước 8: Khách hàng tiến hành đăng nhập và đổi mật khẩu',

            'Tặng thêm 100.000 VNĐ khi khách hàng phát sinh giao dịch: <a href="https://docs.google.com/presentation/d/1oakkOGW60jXwTDDQOweTENzUKMl1FcpmsOTwyXttVvM/edit#slide=id.g201ea6d2925_0_140"> Xem hướng dẫn tại đây </a> '
        ]
    },
    {
        id: 'cake',
        status: 'active',
        linkImg: 'https://storage.googleapis.com/hyperlead-public/production/assets/offers/cake.png',
        name: 'Thẻ Ngân hàng số Cake',
        linkA: 'https://hyperlead.tech/hlGtdX',
        linkIO: 'https://hyperlead.tech/hlSvVZ',
        title: 'Cake Bank - Hướng dẫn thủ tục làm thẻ ATM nhanh chóng',
        desc: [
            'Cake by VPBank là một ngân hàng số miễn phí trọn đời với sứ mệnh mang tới cho khách hàng trải nghiệm dễ dàng, an toàn và bảo mật.',
            'Các đặc điểm của Cake by VPBank:',
            '- Phát hành thẻ miễn phí',
            '- Miễn phí toàn bộ các dịch vụ như chuyển tiền, giao dịch tài chính, quẹt thẻ (POS, mPOS), ....',
            '- Miễn phí thường niên, duy trì thẻ trọn đời',
            '- Miễn phí rút tiền tại tất cả cây ATM',
            '- Thanh toán nước ngoài dễ dàng vì là thẻ Master Card',
            '- Tiết kiệm online thông minh với lãi suất tiền gửi cao nhất thị trường (Super Saver)',
            '- Lãi suất tiền gửi không kỳ hạn: 0,2%/năm',
            '- Lãi suất tiền gửi có kỳ hạn',

            ' ** Quy trình đăng ký ** ',
            'B1: Khách hàng truy cập vào link của HyperLead và chọn mở tài khoản mới',
            'B2: Khách hàng nhập số điện thoại, nhận OTP sms và nhập OTP xác nhận',
            'B3: Khách hàng tiến hành định danh điện tử (eKYC), chụp CMND/CCCD (trước, sau) và chụp chân dung (selfie)',
            'B4: Khách hàng bổ sung thông tin (email, giới tính, tình trạng hôn nhân, nơi cấp CMND/CCCD)',
            'B5: Khách hàng điền tên đăng nhập và mật khẩu',
            'B6: Nhập OTP xác nhận và được chuyển đến màn hình chờ (màn hình chính của Ứng dụng Cake)',
            'B7: Đăng nhập và chọn đăng ký thẻ Visa Credit',
            'B8: Chụp hình khuôn mặt theo hướng dẫn',
            'B9: Ngân hàng số Cake tiến hành xử lý hồ sơ và phê duyệt hạn mức',
            'B10: Tùy chọn mẫu thẻ theo sở thích và nhập thông tin cá nhân theo hướng dẫn',
            'Hướng dẫn mở tài khoản Cake Bank: <a href="https://docs.google.com/presentation/d/1oakkOGW60jXwTDDQOweTENzUKMl1FcpmsOTwyXttVvM/edit#slide=id.g201ea6d2925_0_140"> Xem tại đây </a>',
        ],
    },
    {
        id: 'vpbank',
        status: 'disabled',
        linkImg: 'https://storage.googleapis.com/hyperlead-public/production/assets/offers/vpbank-2.png',
        name: 'Thẻ VPBank',
        linkA: 'https://hyperlead.tech/hlKWUW',
        linkIO: 'https://hyperlead.tech/hlKWUW',
        title: 'VP Bank - Hướng dẫn thủ tục làm thẻ ATM nhanh chóng',
        desc: [
            'Hiện tại ngừng hỗ trợ đăng ký thẻ',
            'VPBank là ngân hàng có tỷ lệ chuyển đổi số lớn nhất trên thị trường hiện nay. Kể từ tháng 7/2021, VPBank cho ra mắt Nền tảng Ngân hàng số toàn năng VPBank NEO để mang đến trải nghiệm hoàn toàn mới mẻ cho khách hàng sử dụng ngân hàng số.',
            'VPBank NEO là Nền tảng Ngân hàng số toàn năng của VPBank, được tích hợp toàn bộ các tiện ích, tính năng của ngân hàng số VPBank Online trước đây, bên cạnh đó còn được kết nối với các đối tác đa dạng thuộc hệ sinh thái của VPBank',
            'VPBank NEO là Nền tảng Ngân hàng số toàn năng duy nhất và tiên tiến nhất hiện nay, sử dụng công nghệ nhận diện sinh trắc học, bảo mật giao dịch với Smart OTP và cung cấp hàng nghìn tiện ích khác chỉ trên một nền tảng số duy nhất',
            '- SIÊU TỐC định danh eKYC 5 giây – Có tài khoản dùng ngay',
            '- MIỄN PHÍ toàn bộ các giao dịch chuyển tiền.',
            '- MIỄN PHÍ thanh toán mọi hóa đơn dịch vụ điện, nước, internet điện thoại, nạp thẻ điện thoại….',
            '- TIỆN ÍCH NGẬP TRÀN mua vé máy bay, đặt phòng khách sạn, thỏa thích mua sắm, trả góp chỉ trên 1 ứng dụng',
            '- ĐẦU TƯ DỄ DÀNG chuyển tiền chứng khoán miễn phí, tiết kiệm trực tuyến đa dạng.','- DUY NHẤT TẠI VIỆT NAM – Duyệt vay tiêu dùng nhanh chóng sau 1 phút đăng kí online, Không cần hồ sơ giấy tờ bản cứng, không cần chứng minh tài chính',
            '- BẢO MẬT AN TOÀN thông tin cá nhân và lịch sử giao dịch.',
            'Cùng nhiều tiện ích khác đang chờ bạn khám phá!',
            'Chỉ với 1 phút đăng ký 100% online, khách hàng có thể dễ dàng quản lý và giao dịch tài chính online tiện lợi, nhanh chóng đồng thời sở hữu vô vàn tính năng vượt trội. Nhanh tay đăng ký VPBank NEO để trải nghiệm ngay hôm nay.',
            
            '** Quy trình đăng ký **',
            '- Bước 1: Người dùng chọn vào ô "Đăng ký ngay',
            '- Bước 2: Người dùng tải App VPBANK NEO và mở App VPBANK NEO trong điều kiện có kết nối mạng wifi, 3G, 4G',
            '- Bước 3:  Chọn Đăng ký mở tài khoản hoặc đăng ký ngay',
            '- Bước 4: Chọn: Mở tài khoản chọn Số Đẹp dành cho khách hàng mới',
            '- Bước 5: Tiến hành nhập thông tin, ocr chứng minh thư, chụp ảnh …',
            '- Bước 6: Nhập mã OTP xác nhận mở tài khoản thành công',
            '- Bước 6: Nhập mã OTP xác nhận mở tài khoản thành công',
            '- Bước 8: Người dùng đăng nhập vào tài khoản thành công'

        ]
    },
    {
        id: 'vnpay',
        status: 'active',
        linkImg: 'https://images02.vietnamworks.com//companyprofile/null/en/Logo_VNPAY.jpg',
        name: 'VNPAY - tặng KH mới 50K',
        linkA: 'https://shorten.asia/3dSQrxYu',
        linkIO: 'https://shorten.asia/3dSQrxYu',
        title: 'VNPAY - Hướng dẫn thủ tục mở thẻ thanh toán nhanh chóng',
        desc: [
            'VNPAY - Ví điện tử đầu tiên dành cho gia đình Việt, đáp ứng đa dạng nhu cầu thanh toán các dịch vụ hàng ngày của bạn và gia đình một cách nhanh chóng, tiện lợi, an toàn.',
            'Quản lý tiện lợi với Ví gia đình, mở ví thành viên cho người thân, đặt hạn mức và theo dõi chi tiêu dễ dàng. Mua sắm cùng VNPAYQR, quét mã VNPAYQR thanh toán siêu nhanh, nhận ưu đãi độc quyền tại hơn 150.000 điểm thanh toán cùng nhiều tính năng khác như chuyển tiền, Nạp tiền điện thoại, Thanh toán hóa đơn, Đặt vé máy bay, Đặt vé tàu, Gọi taxi…',
            'Từ ngày 08/11/2023 đến hết ngày 15/01/2024: VNPAY tặng ngay 50K tiền vào ví + gói quà trị giá 950.000 VND cho KH đăng ký lần đầu và phát sinh 1 giao dịch,',
            ' ** Quy trình đăng ký **',
            'B1: Click vào ô "Đăng ký ngay"',
            'B2: Người dùng tải và cài đặt ví VNPAY',
            'B3: Đăng ký tài khoản ví VNPAY và thực hiện định danh ekyc trên ví VNPAY thành công (bắt buộc)',
            'B4: Người dùng thực hiện liên kết thẻ ghi nợ/tài khoản ngân hàng thành công trên app Ví VNPAY (CPR) (bắt buộc)',
            'B5: gười dùng phát sinh 01 giao dịch thành công (không bao gồm Nạp/ Rút/ Chuyển tiền/Thanh toán Vay tiên dùng/ Mua vé xổ số) từ nguồn tiền Ví trong tháng hoàn thành đăng ký tài khoản hoặc 14 ngày đầu của tháng kế tiếp để nhận 100.000 VNĐ cho tài khoản đăng ký mới.'
        ]
    },
]